Repository oneleif/VaporWebsite, pull requests merged in 2022-09, with the labels that each got.

#23 [Support] Branch Linting
  .github/workflows/branchlint.yml
Labels: enhancement, CI/CD

#25 Update branchlint.yml
  .github/workflows/branchlint.yml
Labels: bug, CI/CD

#26 HTTPS Cookie Security
  README.md
  Sources/App/Controllers/AuthenticationController.swift
  Sources/App/configure.swift
  docker-compose.yml
Labels: bug
